# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/pyther/goeap_proxy
%global goipath         github.com/pyther/goeap_proxy
Version:                0.2.1

%gometa

%global common_description %{expand:
EAP Proxy written in Go.}

%global godocs          README.md

Name:           goeap_proxy
Release:        1%{?dist}
Summary:        EAP Proxy written in Go

License:        MIT

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep -k

%build
BUILD=`date +%FT%T%z`
LDFLAGS="-X main.Version=%{version} -X main.BuildStamp=${BUILD} $LDFLAGS"
%gobuild -o %{gobuilddir}/bin/goeap_proxy %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Jan 24 07:26:18 PST 2021 Matthew Gyurgyik <matthew@gyurgyik.io> - 0.2.0-1
- Initial package

